apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: mysql
type: Opaque
data:
  NAME: dG9kb2Ri  # tododb in base64
  USER: dXNlcg==  # user in base64
  PASSWORD: cGFzc3dvcmQ=  # password in base64
  HOST: bXlzcWwtMA==  # mysql-0 in base64 