apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: mysql
type: Opaque
data:
  root-password: cm9vdHBhc3N3b3Jk  # rootpassword in base64
  mysql-user: dXNlcg==            # user in base64
  mysql-password: cGFzc3dvcmQ=    # password in base64 